### ISSUE TITLE
there are some validation errors in the manifest.... there are none!

### ISSUE THREAD

**Issue by wvmstr** [manifoldjs/manifoldjs-windows10#25]
Warnings (0) 

Suggestions (0)

**Comment by boyofgreen** [comment]
Hey @wvmstr  can you share the URL you are using?  We'll take a look

**Comment by wvmstr** [comment]
www.billthis.com<http://www.billthis.com>
BillThis - mobile business management<http://www.billthis.com/>
Mobile business management for lawn mowers, farriers and equine veterinarians
www.billthis.com



Robert
________________________________

**Comment by boyofgreen** [comment]
Hi Robert,
  I ran that with the CLI and it gave me back errors.  It looks like the first three images use a capital "X" instead of a lowercase "x" for the sizing. 
[error] general     : Manifest validation ERROR      - String does not match pattern: ^[0-9 x]+$ No enum match for: "128X128".(member: /icons/0/sizes).
[error] general     : Manifest validation ERROR      - String does not match pattern: ^[0-9 x]+$ No enum match for: "48X48".(member: /icons/1/sizes).
[error] general     : Manifest validation ERROR      - String does not match pattern: ^[0-9 x]+$ No enum match for: "16X16".(member: /icons/2/sizes).

 I'll need to look into weather that is valid and we are identifying it incorrectly.  Either way, we didn't return the errors and we should have, I'll add a task in to look at this.
  At any rate, if you go for the lowercase on the first three, looks like it all runs.
Thanks,
Jeff

**Comment by wvmstr** [comment]
Yup! It did run and I have submitted my PWA to the Windows App Store.
