### ISSUE TITLE
Error on require in Node 12

### ISSUE THREAD

**Issue by orndorffgrant** [manifoldjs/manifoldjs-windows10#39]
I'm running node 12.10.

Trying to require this package:
```js
var platform = require('pwabuilder-windows10')
```

fails with the following message:
```js
Thrown:
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/grantorndorff/git/coalesce/windows/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/grantorndorff/git/coalesce/windows/node_modules/natives/index.js:55:10)
```

Downgrading to node 10 works and is a good solution for me, but I thought I'd list this as an issue for your and other's awareness.

**Comment by lee-leonardo** [comment]
Hey @orndorffgrant thanks! This is indeed a known issue due to a dependency within Q, which is a promise framework we currently use. We are hoping to spend sometime refactoring out Q in favor of just async await and standard ECMAScript promises.

I'll post here and close out the issue when we do migrate away from Q!
